### ISSUE TITLE
nh error read status

### ISSUE THREAD

**Issue by ebet12** [fdciabdul/InsideHeartz-WhatsApp-Bot#10]
!nh
 [object Object]
        participant

(node:1392) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'status' of undefined
    at C:\Users\ebet\Documents\BOT Mantul\InsideHeartz-WhatsApp-Bot\InsideHeartz-WhatsApp-Bot\node_modules\nana-api\lib\util\Request.js:26:24
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:1392) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)

=>
!randomanime
[object Object]
        participant

https://anime.computerfreaker.cf/f69e989ca66df204754ccbb023aed083.jpg
internal/fs/utils.js:298
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'anime/nime.jpg'
    at Object.openSync (fs.js:465:3)
    at Object.readFileSync (fs.js:368:35)
    at Function.fromFilePath (C:\Users\ebet\Documents\BOT Mantul\InsideHeartz-WhatsApp-Bot\InsideHeartz-WhatsApp-Bot\node_modules\whatsapp-web.js\src\structures\MessageMedia.js:40:28)
    at C:\Users\ebet\Documents\BOT Mantul\InsideHeartz-WhatsApp-Bot\InsideHeartz-WhatsApp-Bot\index.js:1684:27
    at ChildProcess.exithandler (child_process.js:315:5)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1051:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'anime/nime.jpg'
}

C:\Users\ebet\Documents\BOT Mantul\InsideHeartz-WhatsApp-Bot\InsideHeartz-WhatsApp-Bot>

**Comment by fdciabdul** [comment]
make folder anime

**Comment by ebet12** [comment]
Nime.jpg nya pake foto apa bang atau foto anime bebas kah?

**Comment by ebet12** [comment]
Done

**Comment by ebet12** [comment]
[object Object]
        participant

(node:2968) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'status' of undefined
    at C:\Users\ebet\Documents\BOT Mantul\InsideHeartz-WhatsApp-Bot\InsideHeartz-WhatsApp-Bot\node_modules\nana-api\lib\util\Request.js:26:24
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2968) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:2968) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

kalo ini eror apanya bang?
