### ISSUE TITLE
!yt download

### ISSUE THREAD

**Issue by Hendra827** [fdciabdul/InsideHeartz-WhatsApp-Bot#12]
![Screenshot_2020-08-30-12-23-23-55_fb47b6c93b99596be3e79670c6246005](https://user-images.githubusercontent.com/31788233/91651849-d4e85000-eabb-11ea-8985-94c67779720e.jpg)
Itu knpa ya klo Download video yt di atas 100mb error

**Comment by fdciabdul** [comment]
emang limit di whatsapp nya cuma 65mb
