### ISSUE TITLE
(node:9372) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process! spawn usr/bin/google-chrome-stable ENOENT

### ISSUE THREAD

**Issue by MSI0072** [fdciabdul/InsideHeartz-WhatsApp-Bot#14]
Gimana si?

![image](https://user-images.githubusercontent.com/63404067/91875994-bb860600-ec6b-11ea-8290-51d0eb0a996a.png)

**Comment by nenofetch** [comment]
update nodejsmu ke 14/current
