### ISSUE TITLE
(node:9562) UnhandledPromiseRejectionWarning: FetchError: request to https://tools.aqin.my.id/api/brainly/?q=siapa%20penemu%20windows failed, reason: certificate has expired

### ISSUE THREAD

**Issue by MSI0072** [fdciabdul/InsideHeartz-WhatsApp-Bot#15]
brainly eror

![image](https://user-images.githubusercontent.com/63404067/91876901-cd1bdd80-ec6c-11ea-9a02-0b65ec71f740.png)

**Comment by fdciabdul** [comment]
i put the brainly file on PHP File folder , u should upload the file on your hosting and change the url
