### ISSUE TITLE
Error command !lirik

### ISSUE THREAD

**Issue by Hendra827** [fdciabdul/InsideHeartz-WhatsApp-Bot#17]
![Screenshot_2020-09-03-01-29-10-66_fb47b6c93b99596be3e79670c6246005](https://user-images.githubusercontent.com/31788233/92022133-00519000-ed85-11ea-8152-d003e429e580.jpg)

Halo itu cara atasinya gmna kak !lirik selalu error gitu

**Comment by ebet12** [comment]
Aku lancar aja tuh. Cuma perintahnya harus pake - setelah !lirik. Contoh !lirik - faded. Kalo misal !lirik faded jdinya eror

**Comment by ebet12** [comment]
Kalo gk coba instal ulang lgi 'npm i' terus high low masukin perintah 'npm audit fix' baru coba lagi !liriknya

**Comment by Hendra827** [comment]
Iya aku command nya !lirik - faded errornya gitu

**Comment by Hendra827** [comment]
> Kalo gk coba instal ulang lgi `npm i` terus kalo ada bacaan high low masukin perintah `npm audit fix` baru coba lagi !lirik

Ok aku coba dulu

**Comment by ebet12** [comment]
Nungguin suhu aja dah. W baru 1 bulan belajar ngebot 😂😂😂

**Comment by fdciabdul** [comment]
coba ganti api key genius nya pake punyamu sendiri , bikin apikey geniusnya

**Comment by fdciabdul** [comment]
fixed

**Comment by fdciabdul** [comment]
https://github.com/fdciabdul/InsideHeartz-WhatsApp-Bot/commit/6ed4146184cddc40cb667abfd60cdbd68cd64830
