### ISSUE TITLE
text to speech indonesia

### ISSUE THREAD

**Issue by ebet12** [fdciabdul/InsideHeartz-WhatsApp-Bot#19]
else if (msg.body.startsWith("!ttsid")) {
  msg.reply('ketik !menu untuk melihat list menu bot');
  var text = msg.body.split("!ttsid ")[1];
  var gtts = require('node-gtts')('id', true);
  var path = require('path');
  var text1 = text.slice(6);
  text1 = suara;
  var suara = text.replace(/!ttsid/g, text1);
  var filepath = path.join(__dirname, 'bacot.wav');
  
  
/*
 * save audio file
 */

gtts.save(filepath, suara, function() {
  console.log(`${filepath} MP3 SAVED!`)
});
await new Promise(resolve => setTimeout(resolve, 500));

	if(suara.length > 200){ // check longness of text, because otherways google translate will give me a empty file
  msg.reply("Text to long, split in text of 200 characters")
}else{

  const media = MessageMedia.fromFilePath(filepath);

	chat.sendMessage(media);

};

}

tambahkan `"node-gtts": "^2.0.2",` dipackage.json kemudian `npm init` lalu `npm i`

**Comment by fdciabdul** [comment]
yang lebih simple bisa di edit langsung di folder text-to-speech di node_modules

tapi bisa open pull request kok pak

**Comment by ebet12** [comment]
Blm terlalu paham main node module. Itu aja nyoba" node-gtts sambil liat script org sambil mahamin alur node gtts nya. Maklum baru belajar javascript 😅😅😅
