### ISSUE TITLE
 TypeError: Cannot read property 'split' of undefined  

### ISSUE THREAD

**Issue by chicken999** [fdciabdul/InsideHeartz-WhatsApp-Bot#21]
Hi , the command !makeff isnt working properly for some reason.
Output of: !makeff chicken

(node:14456) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
    at Client.<anonymous> (C:\Users\arr98\wabots\InsideHeartz-WhatsApp-Bot-master\index.js:367:30) 
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:14456) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:14456) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by fdciabdul** [comment]
!makeff [Nick] Your Name
