### ISSUE TITLE
Error Play Lagu

### ISSUE THREAD

**Issue by brillyandev** [fdciabdul/InsideHeartz-WhatsApp-Bot#22]
Pesan Error !play & !ytmp3

(node:13792) UnhandledPromiseRejectionWarning: Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('Status code: 429')
    at YoutubeMp3Downloader.emit (events.js:304:17)

sebelumnya bisa, sekarang sudah tidak bisa.. respond error seperti diatas.
ada solusi untuk fixnya bagaimana ?
padahal path env sudah diatur ke C:\ffmpeg\bin .

**Comment by fdciabdul** [comment]
kena block youtube

**Comment by fdciabdul** [comment]
> Pesan Error !play & !ytmp3
> 
> (node:13792) UnhandledPromiseRejectionWarning: Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('Status code: 429')
> at YoutubeMp3Downloader.emit (events.js:304:17)
> 
> sebelumnya bisa, sekarang sudah tidak bisa.. respond error seperti diatas.
> ada solusi untuk fixnya bagaimana ?
> padahal path env sudah diatur ke C:\ffmpeg\bin .

btw udah liat ini ? https://github.com/fdciabdul/InsideHeartz-WhatsApp-Bot#free-version

gw kan dah bilang ini free jangan dijual , kalopun di jual cuan nya bagi bagi lah ke ane sebagai dev aslinya wkwk

**Comment by brillyandev** [comment]
bukan jual sob, ane buat bot untuk dipake sama orang :v
