### ISSUE TITLE
error saat $npm i

### ISSUE THREAD

**Issue by rafi7797** [fdciabdul/InsideHeartz-WhatsApp-Bot#36]
setelah saya klik perintah npm i langsung seperti ini
![Untitled](https://user-images.githubusercontent.com/72056364/94506343-b652b180-023f-11eb-96e8-b1bb5b1c8b66.png)

**Comment by fdciabdul** [comment]
itu dependencies sharp ya , keknya versi nodejs kurang

coba liat versi nodejs nya

**Comment by rafi7797** [comment]
update nodejs kah? min

**Comment by rafi7797** [comment]
sol
