### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by TheSploit** [fdciabdul/InsideHeartz-WhatsApp-Bot#44]
Ngatasinnya gimana ya?
D:\MaFile\WA Bot\InsideHeartz-WhatsApp-Bot-master\node_modules\sharp\src\stats.cc(130,1): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [D:\MaFile\WA Bot\InsideHeartz-WhatsApp-Bot-master\node_modules\sharp\build\s
harp.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\MaCRACK\NgeHek\Tools\WA Bot\InsideHeartz-WhatsApp-Bot-master\node_modules\sharp
gyp ERR! node -v v14.13.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.22.1 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.22.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2020-10-02T16_25_26_990Z-debug.log

**Comment by fdciabdul** [comment]
pake nodejs versi berapa ?

**Comment by TheSploit** [comment]
> pake nodejs versi berapa ?

14.13.0

**Comment by fdciabdul** [comment]
coba ketik `npm cache clean --force`

lalu delete semua file di folder nya , trus download lagi repository ini

**Comment by dzakijo1** [comment]
> coba ketik `npm cache clean --force`
> 
> lalu delete semua file di folder nya , trus download lagi repository ini

bang, ane boleh minta case yang ptl ga? ane copas case abang yang ptl malah error di input ke bot ane :(

**Comment by fdciabdul** [comment]
> > coba ketik `npm cache clean --force`
> > lalu delete semua file di folder nya , trus download lagi repository ini
> 
> bang, ane boleh minta case yang ptl ga? ane copas case abang yang ptl malah error di input ke bot ane :(

case apa

**Comment by TheSploit** [comment]
> coba ketik `npm cache clean --force`
> 
> lalu delete semua file di folder nya , trus download lagi repository ini

Repository ini? maksudnya node_modules jadi setelah npm cache clean --force trus npm i/install ya?

**Comment by fdciabdul** [comment]
> > coba ketik `npm cache clean --force`
> > lalu delete semua file di folder nya , trus download lagi repository ini
> 
> Repository ini? maksudnya node_modules jadi setelah npm cache clean --force trus npm i/install ya?

betul

**Comment by TheSploit** [comment]
> > > coba ketik `npm cache clean --force`
> > > lalu delete semua file di folder nya , trus download lagi repository ini
> > 
> > 
> > Repository ini? maksudnya node_modules jadi setelah npm cache clean --force trus npm i/install ya?
> 
> betul

ttp gabisa
