### ISSUE TITLE
YTDownloader menu,brainly,lyric search error

### ISSUE THREAD

**Issue by Mreror404** [fdciabdul/InsideHeartz-WhatsApp-Bot#5]
$ node index.js
(node:4048) ExperimentalWarning: The fs.promises API is experimental
[ 21:41:17 ] Mqtt topic subscribed!
[ 21:42:05 ] Authenticated Success!
[ 21:42:05 ] Whatsapp bot ready!
 [object Object]
        participant

 [object Object]
        participant

 [object Object]
        participant

 [object Object]
        participant

video id =  KrUOhKLlkf4
                                                                                                                            at TLSWrap.onStreamRead (internal/stream_bas
e_commons.js:111:27)
(node:4048) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, o
r by rejecting a promise which was not handled with .catch(). (rejection id: 2)
 [object Object]
        participant

 [object Object]
        participant

(node:4048) UnhandledPromiseRejectionWarning: FetchError: invalid json response body at https://tools.aqin.my.id/cgi-sys/suspendedpage.cgi?q=kodok%20bernafas%20mengguna
kan%20apa reason: Unexpected token < in JSON at position 0
    at C:\xampp\htdocs\InsideHeartz-WhatsApp-Bot\node_modules\node-fetch\lib\index.js:272:32
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:4048) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, o
r by rejecting a promise which was not handled with .catch(). (rejection id: 4)
 [object Object]
        participant

video id =  KrUOhKLlkf4
 [object Object]
        participant

 [object Object]
        participant

8uy7G2JXVSA
8uy7G2JXVSA
(node:4048) UnhandledPromiseRejectionWarning: Error [ERR_UNHANDLED_ERROR]: Unhandled error. (read ECONNRESET)
    at YoutubeMp3Downloader.emit (events.js:178:17)
    at Object.callback (C:\xampp\htdocs\InsideHeartz-WhatsApp-Bot\node_modules\youtube-mp3-downloader\lib\YoutubeMp3Downloader.js:66:18)
    at C:\xampp\htdocs\InsideHeartz-WhatsApp-Bot\node_modules\youtube-mp3-downloader\node_modules\async\dist\async.js:1311:26
    at C:\xampp\htdocs\InsideHeartz-WhatsApp-Bot\node_modules\youtube-mp3-downloader\node_modules\async\dist\async.js:321:20
    at C:\xampp\htdocs\InsideHeartz-WhatsApp-Bot\node_modules\youtube-mp3-downloader\lib\YoutubeMp3Downloader.js:34:13
    at C:\xampp\htdocs\InsideHeartz-WhatsApp-Bot\node_modules\youtube-mp3-downloader\lib\YoutubeMp3Downloader.js:85:13
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:4048) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, o
r by rejecting a promise which was not handled with .catch(). (rejection id: 5)
![image](https://user-images.githubusercontent.com/33925496/90150779-35834780-ddb0-11ea-940e-4512930493c2.png)

**Comment by fdciabdul** [comment]
untuk brainly.  silahkan upload file brainly.php ke hostingan , atau pakai xampp untuk menjalan kan filenya 

dan untuk youtube download , silahkan update libary nya dengan cara 

`npm update`

**Comment by Mreror404** [comment]
![image](https://user-images.githubusercontent.com/33925496/90156839-26ec5e80-ddb7-11ea-8930-96075dc29ce1.png)
ini kenapa ya gan?

**Comment by fdciabdul** [comment]
> ![image](https://user-images.githubusercontent.com/33925496/90156839-26ec5e80-ddb7-11ea-8930-96075dc29ce1.png)
> ini kenapa ya gan?

itu mau ngapain

**Comment by Mreror404** [comment]
> untuk brainly. silahkan upload file brainly.php ke hostingan , atau pakai xampp untuk menjalan kan filenya
> 
> dan untuk youtube download , silahkan update libary nya dengan cara
> 
> `npm update`

mau update library youtube download

**Comment by fdciabdul** [comment]
coba langsung npm update youtube-mp3-downloader
